### ISSUE TITLE
Fatal Error Upgrading / Installing 1.1.1 to 1.3.0 (PHP 8.1 and MySQL 5)

### ISSUE THREAD

**Issue by NB-Core** [NB-Core/lotgd#15]
### Discussed in https://github.com/NB-Core/lotgd/discussions/14

<div type='discussions-op-text'>

<sup>Originally posted by **ironmangary** September 22, 2023</sup>
I am attempting to upgrade LotGD from v1.1.1 +nb to 1.3.0 under PHP 8.1 and MySQL 5.7.23.  When I click "Save Settings" at step 9 (modules), I get the following fatal error:

Fatal error: Uncaught mysqli_sql_exception: Duplicate column name 'function' in /home4/MUNGED_USERNAME/earthgonewrong.com/lib/dbwrapper_mysqli_proc.php:23 Stack trace: #0 /home4/MUNGED_USERNAME/earthgonewrong.com/lib/dbwrapper_mysqli_proc.php(23): mysqli_query(Object(mysqli), 'ALTER TABLE mod...') #1 /home4/MUNGED_USERNAME/earthgonewrong.com/lib/tabledescriptor.php(107): db_query('ALTER TABLE mod...') #2 /home4/MUNGED_USERNAME/earthgonewrong.com/lib/installer/installer_stage_9.php(14): synctable('module_hooks', Array, true) #3 /home4/MUNGED_USERNAME/earthgonewrong.com/installer.php(152): require_once('/home4/MUNGED_USERNAME...') #4 {main} thrown in /home4/MUNGED_USERNAME/earthgonewrong.com/lib/dbwrapper_mysqli_proc.php on line 23

I'm not sure of the proper solution and would appreciate any guidance.  Thanks!</div>

**Comment by NB-Core** [comment]
Key takeaways:

Reserved mysql names aren't handled (ticked) in lib/tabledescriptor.php (now at least a bit)
sql statements had INSERT into the settings table to existing settings (in installer stages) that missed an IGNORE
one minor fix was a log-spamming missing check for a dynamic-variable-naming-call

**Comment by NB-Core** [comment]
Fixed.
